# Generated by Django 6.0.6 on 2026-06-21 19:47

import api.validators
import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=256, unique=True, verbose_name='Наименование модели и марки')),
                ('capacity', models.PositiveIntegerField(validators=[api.validators.capacity], verbose_name='Номинальная вместимость')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.EmailField(max_length=256, unique=True, verbose_name='email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ATP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Название компании')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_wiki_url', models.URLField(unique=True, validators=[api.validators.route_wiki_url], verbose_name='Урл-адрес маршрута')),
                ('capacity_class', models.CharField(choices=[('very_big', 'very_big'), ('big', 'big'), ('medium', 'medium'), ('small', 'small'), ('very_small', 'very_small')], max_length=14, verbose_name='Класс вместимости')),
                ('units_per_route', models.PositiveIntegerField(verbose_name='Количество транспорта на маршруте')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата заявки')),
                ('atp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.atp', verbose_name='Транспортная компания')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('from_atp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.atp', verbose_name='От кого')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.lead', verbose_name='Лиды')),
                ('to', models.ManyToManyField(related_name='recepients', to='api.atp', verbose_name='Кому')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bort', models.PositiveIntegerField(unique=True, verbose_name='Бортовой номер')),
                ('color', models.CharField(choices=[('white', 'white'), ('purple', 'purple'), ('blue', 'blue'), ('green', 'green'), ('red', 'red'), ('orange', 'orange'), ('yellow', 'yellow')], max_length=16, verbose_name='Цвет')),
                ('atp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.atp', verbose_name='Транспортная компания')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.bus', verbose_name='Наименование подвижной единицы')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.lead', verbose_name='Заявка')),
            ],
        ),
    ]
