# Generated by Django 6.0.6 on 2026-07-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='from_atp',
            new_name='atp',
        ),
        migrations.AddField(
            model_name='lead',
            name='route_no',
            field=models.CharField(default=258, verbose_name='Номер маршрута'),
        ),
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='color',
            field=models.CharField(choices=[('white', 'white'), ('purple', 'purple'), ('blue', 'blue'), ('green', 'green'), ('red', 'red'), ('orange', 'orange'), ('yellow', 'yellow'), ('pink', 'pink')], max_length=16, verbose_name='Цвет'),
        ),
    ]
