# Generated by Django 6.0.6 on 2026-07-18 22:44

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_from_atp_message_atp_lead_route_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='route_no',
            field=models.CharField(default=api.models.assign_route_no, verbose_name='Номер маршрута'),
        ),
    ]
