# Generated by Django 6.0.6 on 2026-07-18 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_lead_route_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='route_no',
        ),
    ]
