# Generated by Django 6.0.6 on 2026-07-18 22:58

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_lead_route_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='route_no',
            field=models.CharField(default=api.models.assign_route_no, verbose_name='Номер маршрута'),
        ),
    ]
