# Generated by Django 6.0.6 on 2026-07-18 23:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_lead_route_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='route_no',
            field=models.CharField(default=api.models.assign_route_no, unique=True, verbose_name='Номер маршрута'),
        ),
    ]
