# Generated by Django 6.0.6 on 2026-06-21 19:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='jti')),
                ('active', models.BooleanField(default=True, verbose_name='Статус вывода из строя')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('userdevice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.userdevice', verbose_name='Владелец')),
            ],
        ),
    ]
