# Generated by Django 6.0.6 on 2026-06-21 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64, verbose_name='Отпечаток устройства')),
                ('ip', models.CharField(max_length=50, verbose_name='ip адрес')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fingerprint', 'ip'), name='device')],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device', verbose_name='Из какого устройства')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто пользуется')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_id', 'device_id'), name='whose')],
            },
        ),
    ]
