from django.urls import path, re_path

from api.views import (
    ATPCreate,
    ATPDelete,
    ATPEdit,
    ATPForAcceptingLeadParam, 
    ATPView,
    Buses,
    BusCathegory,
    BusColors,
    BusUnitView,
    BusUnitCreate,
    BusUnitDelete,
    BusUnitEdit,
    Chats,
    LeadView,
    LeadCreate,
    LeadDelete,
    LeadPropsEdit,
    LeadUnitSet,
    MessageCreate,
    MessageDelete,
    MessageUpdate,
    MessageView,
    ModifyLeadUnitSet,
    MyAcceptedLeads, 
    MyBusUnits, 
    MyCreatedLeads,
    Logout,
    RefreshToken,
    Signin,
    Signup,
    ShoutBox,
    UnitsForAcceptingLead,
    UncoveredLeads, 
)

urlpatterns = [
    path("logout", Logout.as_view(), name="logout"),
    path("signin", Signin.as_view(), name="signin"),
    path("signup", Signup.as_view(), name="signup"),
    path("atp/create", ATPCreate.as_view(), name="atp_create"),
    path("atp/delete", ATPDelete.as_view(), name="atp_delete"),
    path("atp/edit", ATPEdit.as_view(), name="atp_edit"),
    path("atp-accepting-lead/<str:cc>", ATPForAcceptingLeadParam.as_view(), name="atp-accepting-lead"),
    path("buses", Buses.as_view(), name="buses"),
    path("buses/colors", BusColors.as_view({'get': 'get'}), name="bus_colors"),
    path("buses/cathegory", BusCathegory.as_view({'get': 'get'}), name="bus_cathegory"),
    path("chats", Chats.as_view(), name="chats"),
    path("chat/<int:id>", ShoutBox.as_view(), name="chat"),
    path("lead/create", LeadCreate.as_view(), name="lead_create"),
    path("lead/<int:id>", LeadView.as_view(), name="lead_view"),
    path("lead/<int:id>/delete", LeadDelete.as_view(), name="lead_delete"),
    path("lead/<int:id>/edit", LeadPropsEdit.as_view(), name="lead_edit"),
    path("lead/<int:id>/unit-set", LeadUnitSet.as_view(), name="lead_unit_set"),
    path("lead/<int:id>/unit-set/modify", ModifyLeadUnitSet.as_view(), name="modify_lead_unit_set"),
    path("my-accepted-leads", MyAcceptedLeads.as_view(), name="my-accepted-leads"),
    path("my-buses", MyBusUnits.as_view(), name="my-buses"),
    path("my-created-leads", MyCreatedLeads.as_view(), name="my-created-leads"),
    path("profile", ATPView.as_view(), name="profile"),
    path("refresh-token", RefreshToken.as_view(), name="refresh-token"),
    path("shoutbox", ShoutBox.as_view(), name="shoutbox"),
    path("uncovered-leads", UncoveredLeads.as_view(), name="uncovered-leads"),
    path("unit/<int:id>", BusUnitView.as_view(), name="unit_view"),
    path("unit/<int:id>/edit", BusUnitEdit.as_view(), name="unit_edit"),
    path("unit/<int:id>/delete", BusUnitDelete.as_view(), name="unit_delete"),
    path("unit-accepting-lead/<str:cc>", UnitsForAcceptingLead.as_view(), name="unit-accepting-lead"),
    path("unit/create", BusUnitCreate.as_view(), name="unit_create")
]