server {
    listen 80 default_server; # default_server принудительно гасит все остальные конфиги
    server_name _;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}